---
network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s8:
      addresses:
        - 192.168.255.1/30
      routes:
        - to: 192.168.0.0/30
          via: 192.168.255.2
        - to: 192.168.255.0/29
          via: 192.168.255.2
    enp0s19:
      addresses:
        - 192.168.60.10/24