global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'prometheus_master'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node_exporter_monitor'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']
  - job_name: 'node_exporter_frontend'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.10.60.1:9100']
  - job_name: 'node_exporter_backend1'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.10.60.2:9100']
  - job_name: 'node_exporter_backend2'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.10.60.3:9100']
  - job_name: 'node_exporter_db1'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.10.60.4:9100']
  - job_name: 'node_exporter_db2'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.10.60.5:9100']
  - job_name: 'node_exporter_logserver'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.10.60.7:9100']