Vagrant.configure(2) do |config|
  config.vm.define "kernel-update" do |srv| # Имя виртуальной машины в vagrant
    srv.vm.box = "centos/stream8" # Указываем какой образ (box) используем для создания виртуальной машины
    srv.vm.synced_folder "./", "/vagrant" # Файлы из текуший каталог хостовой машины будут скопированы в /vagrant виртуальной машины
    srv.vm.hostname = "task2-centos" # Hostname внутри самой машины
    srv.vm.provider "virtualbox" do |vb| # Используемое средство виртуализации (гипервизор)
      vb.memory = "2048" # Оперативная память, выделяемая виртуальной машине
      vb.cpus = "2" # Количестро ядер, выделяемых виртуальной машине
      vb.name = "Task2-centos" # Имя виртуальной машины в VirtualBox
    end

  config.vm.provision 'shell', reboot: true, inline: <<-SHELL # Запуск команд обновления ядра после развёртывания виртуальной машины
    echo "Текущая версия ядра: $(uname -r)"
    echo =========================================================
    echo Подключение репозитория ELRepo.org
    yum install -y https://www.elrepo.org/elrepo-release-8.el8.elrepo.noarch.rpm
    echo =========================================================
    echo Установка последней версии ядра из репозитория ELRepo.org
    yum --enablerepo elrepo-kernel install kernel-ml -y
    echo =========================================================
    echo Обновление конфигурации загрузчика
    grub2-mkconfig -o /boot/grub2/grub.cfg
    echo =========================================================
    echo Устанавливаем загрузку нового ядра по умолчанию
    grub2-set-default 0
  SHELL
  config.vm.provision 'shell', inline: "echo Версия ядра после обновления: $(uname -r)" # Проверка новой версии ядра
  end
end