Vagrant.configure(2) do |config|
  config.vm.define "kernel-update" do |srv| # Имя виртуальной машины в vagrant
    srv.vm.box = "centos/stream8" # Указываем какой образ (box) используем для создания виртуальной машины
    srv.vm.synced_folder "./", "/vagrant" # Файлы из текуший каталог хостовой машины будут скопированы в /vagrant виртуальной машины
    srv.vm.hostname = "first-centos" # Hostname внутри самой машины
    srv.vm.provider "virtualbox" do |vb| # Используемое средство виртуализации (гипервизор)
      vb.memory = "2048" # Оперативная память, выделяемая виртуальной машине
      vb.cpus = "2" # Количестро ядер, выделяемых виртуальной машине
      vb.name = "Task1-centos" # Имя виртуальной машины в VirtualBox
    end
  end
end