{
 "title": "Vadim Skobelev",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"192.168.50.11:9100\", mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"192.168.50.11:9100\"}[$__rate_interval])))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"192.168.50.11:9100\", job=\"node_exporter_centos\"} / 1024 / 1024",
     "legendFormat": "Total memory"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"192.168.50.11:9100\", job=\"node_exporter_centos\"} / 1024 / 1024",
     "legendFormat": "Available memory"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"192.168.50.11:9100\", job=\"node_exporter_centos\"} / 1024 / 1024",
     "legendFormat": "Memory cached"
    }
   ]
  },
  {
   "title": "DISK",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"192.168.50.11:9100\", job=\"node_exporter_centos\", device=\"/dev/sda1\"} / 1024 / 1024",
     "legendFormat": "Total"
    },
    {
     "expr": "node_filesystem_avail_bytes{instance=\"192.168.50.11:9100\", job=\"node_exporter_centos\", device=\"/dev/sda1\"} / 1024 / 1024",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "SWAP",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"192.168.50.11:9100\", job=\"node_exporter_centos\"} / 1024 / 1024",
     "legendFormat": "SWAP total"
    },
    {
     "expr": "node_memory_SwapCached_bytes{instance=\"192.168.50.11:9100\", job=\"node_exporter_centos\"} / 1024 / 1024",
     "legendFormat": "SWAP cached"
    }
   ]
  },
  {
   "title": "NETWORK",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"192.168.50.11:9100\", job=\"node_exporter_centos\", device=~\"eth0|eth1\"}[1m])",
     "legendFormat": "Receive {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"192.168.50.11:9100\", job=\"node_exporter_centos\", device=~\"eth0|eth1\"}[1m])",
     "legendFormat": "Transmit {{device}}"
    }
   ]
  }
 ]
}