# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "centos/7"
  
    config.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end
  
    config.vm.define "server" do |server|
      server.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "net1"
      server.vm.hostname = "server"
      server.vm.network "forwarded_port", guest: 9090, host: 9090
      server.vm.network "forwarded_port", guest: 3000, host: 3000

      server.vm.provision 'shell', inline: <<-SHELL
      #1 июля 2024 прекратилась поддержка Centos 7, поэтому mirrorlist.centos.org более не доступен.
      #Используем vault.centos.org вместо mirrorlist.centos.org
      sed -i s/mirror.centos.org/vault.centos.org/g /etc/yum.repos.d/*.repo
      sed -i s/^#.*baseurl=http/baseurl=http/g /etc/yum.repos.d/*.repo
      sed -i s/^mirrorlist=http/#mirrorlist=http/g /etc/yum.repos.d/*.repo

      # Устанавливаем вспомогательные пакеты и скачиваем Prometheus
      yum update -y
      yum install -y wget
      wget -q https://github.com/prometheus/prometheus/releases/download/v2.44.0/prometheus-2.44.0.linux-amd64.tar.gz
      
      # Создаем пользователя и нужные каталоги, настраиваем для них владельцев
      useradd --no-create-home --shell /bin/false prometheus
      mkdir /etc/prometheus
      mkdir /var/lib/prometheus
      chown prometheus:prometheus /etc/prometheus
      chown prometheus:prometheus /var/lib/prometheus

      # Распаковываем архив, для удобства переименовываем директорию и копируем бинарники в /usr/local/bin
      tar -xvzf prometheus-2.44.0.linux-amd64.tar.gz
      mv prometheus-2.44.0.linux-amd64 prometheuspackage
      cp prometheuspackage/prometheus /usr/local/bin/
      cp prometheuspackage/promtool /usr/local/bin/

      # Меняем владельцев у бинарников
      chown prometheus:prometheus /usr/local/bin/prometheus
      chown prometheus:prometheus /usr/local/bin/promtool

      # По аналогии копируем библиотеки
      cp -r prometheuspackage/consoles /etc/prometheus
      cp -r prometheuspackage/console_libraries /etc/prometheus
      chown -R prometheus:prometheus /etc/prometheus/consoles
      chown -R prometheus:prometheus /etc/prometheus/console_libraries

      # Создаем файл конфигурации
      bash -c cat <<EOF > /etc/prometheus/prometheus.yml
global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'prometheus_master'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node_exporter_centos'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.50.11:9100']
EOF

      chown prometheus:prometheus /etc/prometheus/prometheus.yml

      # Настраиваем сервис
      bash -c cat <<EOF > /etc/systemd/system/prometheus.service
[Unit]
Description=Prometheus
Wants=network-online.target
After=network-online.target

[Service]
User=prometheus
Group=prometheus
Type=simple
ExecStart=/usr/local/bin/prometheus \
--config.file /etc/prometheus/prometheus.yml \
--storage.tsdb.path /var/lib/prometheus/ \
--web.console.templates=/etc/prometheus/consoles \
--web.console.libraries=/etc/prometheus/console_libraries

[Install]
WantedBy=multi-user.target
EOF

      systemctl daemon-reload
      systemctl start prometheus
      systemctl enable prometheus
      systemctl status prometheus

      # Установка Grafana
      yum install -y https://dl.grafana.com/enterprise/release/grafana-enterprise-11.1.4-1.x86_64.rpm
      systemctl daemon-reload
      systemctl start grafana-server
      systemctl enable grafana-server
      
      SHELL
  
    end
  
    config.vm.define "client" do |client|
      client.vm.network "private_network", ip: "192.168.50.11", virtualbox__intnet: "net1"
      client.vm.hostname = "client"
      client.vm.network "forwarded_port", guest: 9100, host: 9100

      client.vm.provision 'shell', inline: <<-SHELL
      #1 июля 2024 прекратилась поддержка Centos 7, поэтому mirrorlist.centos.org более не доступен.
      #Используем vault.centos.org вместо mirrorlist.centos.org
      sed -i s/mirror.centos.org/vault.centos.org/g /etc/yum.repos.d/*.repo
      sed -i s/^#.*baseurl=http/baseurl=http/g /etc/yum.repos.d/*.repo
      sed -i s/^mirrorlist=http/#mirrorlist=http/g /etc/yum.repos.d/*.repo

      # Скачиваем и распаковываем Node Exporter
      yum install -y wget
      wget -q https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz
      tar xzfv node_exporter-1.5.0.linux-amd64.tar.gz

      # Создаем пользователя, перемещаем бинарник в /usr/local/bin
      useradd -rs /bin/false nodeusr
      mv node_exporter-1.5.0.linux-amd64/node_exporter /usr/local/bin/

      # Создаем сервис
      bash -c cat <<EOF > /etc/systemd/system/node_exporter.service
[Unit]
Description=Node Exporter
After=network.target

[Service]
User=nodeusr
Group=nodeusr
Type=simple
ExecStart=/usr/local/bin/node_exporter

[Install]
WantedBy=multi-user.target
EOF

      # Запускаем сервис
      systemctl daemon-reload
      systemctl start node_exporter
      systemctl enable node_exporter
      
      SHELL

    end
  end