---
- hosts: all
  become: yes
  tasks:
   - name: Set repository
     ansible.builtin.shell: sed -i s/mirror.centos.org/vault.centos.org/g /etc/yum.repos.d/*.repo &&
       sed -i s/^#.*baseurl=http/baseurl=http/g /etc/yum.repos.d/*.repo &&
       sed -i s/^mirrorlist=http/#mirrorlist=http/g /etc/yum.repos.d/*.repo

   - name: Install packages
     ansible.builtin.yum:
       name:
         - bind
         - bind-utils
       state: latest
       update_cache: true

   - name: Start chronyd
     ansible.builtin.systemd:
       name: chronyd
       state: restarted
       enabled: true

   - name: Copy transferkey to all servers and the client
     ansible.builtin.copy:
       src: named.zonetransfer.key
       dest: /etc/named.zonetransfer.key
       owner: root
       group: named
       mode: 0644

- hosts: ns01
  become: yes
  tasks:
    - name: Copy named.conf
      ansible.builtin.copy:
        src: master-named.conf
        dest: /etc/named.conf
        owner: root
        group: named
        mode: 0640

    - name: Copy zones
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /etc/named/
        owner: root
        group: named
        mode: 0660
      with_items:
        - named.ddns.lab
        - named.dns.lab
        - named.dns.lab.client
        - named.dns.lab.rev
        - named.newdns.lab

    - name: Copy resolv.conf to the servers
      ansible.builtin.template:
        src: servers-resolv.conf.j2
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: 0644
  
    - name: Set /etc/named permissions
      ansible.builtin.file:
        path: /etc/named
        owner: root
        group: named
        mode: 0670

    - name: Ensure named is running and enabled
      ansible.builtin.systemd:
        name: named
        state: restarted
        enabled: true

- hosts: ns02
  become: yes
  tasks:
    - name: Copy named.conf
      ansible.builtin.copy:
        src: slave-named.conf
        dest: /etc/named.conf
        owner: root
        group: named
        mode: 0640

    - name: Copy resolv.conf to the servers
      ansible.builtin.template:
        src: servers-resolv.conf.j2
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: 0644

    - name: Set /etc/named permissions
      ansible.builtin.file:
        path: /etc/named
        owner: root
        group: named
        mode: 0670

    - name: Ensure named is running and enabled
      ansible.builtin.systemd:
        name: named
        state: restarted
        enabled: true
    
- hosts: client,client2
  become: yes
  tasks:
    - name: Copy resolv.conf to the client
      ansible.builtin.copy:
        src: client-resolv.conf
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: 0644

    - name: Copy rndc conf file
      ansible.builtin.copy:
         src: rndc.conf
         dest: /home/vagrant/rndc.conf
         owner: vagrant
         group: vagrant
         mode: 0644

    - name: Copy motd to the client
      ansible.builtin.copy:
        src: client-motd
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644
