MACHINES = {
    :frontend => {
        :box_name => "centos/7",
        :vm_name => "frontend",
        :memory => "8000",
        :cpus => "2",
        :net => [
                    #ip, adpter, netmask, virtualbox__intnet
                    ["10.10.60.1", 2, "255.255.255.240", "intranet"], # Local network
                    ["192.168.63.10", 3, "255.255.255.252"], # External network emulation
                    ["192.168.60.10", 8, "255.255.255.0"],
                ]
    },

    :backend1 => {
        :box_name => "centos/7",
        :vm_name => "backend1",
        :memory => "8000",
        :cpus => "2",
        :net => [
                    ["10.10.60.2", 2, "255.255.255.240", "intranet"],
                    ["192.168.60.11", 8, "255.255.255.0"],
                ]
    },

    :backend2 => {
        :box_name => "centos/7",
        :vm_name => "backend2",
        :memory => "8000",
        :cpus => "2",
        :net => [
                    ["10.10.60.3", 2, "255.255.255.240", "intranet"],
                    ["192.168.60.12", 8, "255.255.255.0"],
                ]
    },

    :db1 => {
        :box_name => "centos/7",
        :vm_name => "db1",
        :memory => "8000",
        :cpus => "2",
        :net => [
                    ["10.10.60.4", 2, "255.255.255.240", "intranet"],
                    ["192.168.60.13", 8, "255.255.255.0"],
                ]
    },

    :db2 => {
        :box_name => "centos/7",
        :vm_name => "db2",
        :memory => "8000",
        :cpus => "2",
        :net => [
                    ["10.10.60.5", 2, "255.255.255.240", "intranet"],
                    ["192.168.60.14", 8, "255.255.255.0"],
                ]
    },

    :monitor => {
        :box_name => "centos/7",
        :vm_name => "monitor",
        :memory => "8000",
        :cpus => "2",
        :net => [
                    ["10.10.60.6", 2, "255.255.255.240", "intranet"],
                    ["192.168.60.15", 8, "255.255.255.0"],
                ]
    },

    :logserver => {
        :box_name => "centos/7",
        :vm_name => "logserver",
        :memory => "8000",
        :cpus => "2",
        :net => [
                    ["10.10.60.7", 2, "255.255.255.240", "intranet"],
                    ["192.168.60.16", 8, "255.255.255.0"],
                ]
    },
}

Vagrant.configure("2") do |config|
    MACHINES.each do |boxname, boxconfig|
        config.vbguest.auto_update = false
        config.vm.boot_timeout = 600
        config.ssh.keep_alive = true
        config.vm.define boxname do |box|
            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxconfig[:vm_name]
            box.vm.provider "virtualbox" do |v|
                v.memory = boxconfig[:memory]
                v.cpus = boxconfig[:cpus]
            end

            boxconfig[:net].each do |ipconf|
            box.vm.network("private_network", ip: ipconf[0], adapter: ipconf[1], netmask: ipconf[2], virtualbox__intnet: ipconf[3])
            end

            if boxconfig[:vm_name] == "monitor" 
                box.vm.network "forwarded_port", guest:3000, host: 3000 
             end

            if boxconfig[:vm_name] == "logserver"
                box.vm.provision "ansible" do |ansible|
                    ansible.playbook = "ansible/provision.yml"
                    ansible.inventory_path = "ansible/hosts"
                    ansible.config_file = "ansible/ansible.cfg"
                    ansible.limit = "all"
                end
            end

            box.vm.provision "shell", inline: <<-SHELL
                mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
            SHELL
        end
    end
end