
Vagrant.configure("2") do |config|
    config.vbguest.auto_update = false
    config.vm.box = "ubuntu/jammy64"
    config.vm.define "servervpn" do |server|
        server.vm.host_name = "servervpn"
        server.vm.network "private_network", ip: "192.168.60.10"
    
        server.vm.provision "ansible" do |ansible|
            ansible.playbook = "ansible/provision_ras.yml"
            ansible.inventory_path = "ansible/hosts"
            ansible.host_key_checking = "false"
            ansible.limit = "all"
        end
    end
end