---
- name: Set up VM
  hosts: DynamicWeb
  become: true
  gather_facts: false

  tasks:
   - name: Install docker packages
     become: true
     ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
     with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
     tags:
       - docker

   - name: Add Docker s official GPG key
     become: true
     ansible.builtin.apt_key:
       url: https://download.docker.com/linux/ubuntu/gpg
       state: present
     tags:
       - docker

   - name: Verify that we have the key with the fingerprint
     become: true
     ansible.builtin.apt_key:
       id: 0EBFCD88
       state: present
     tags:
       - docker

   - name: Set up the stable repository
     become: true
     ansible.builtin.apt_repository:
       repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
       state: present
       update_cache: yes
     tags:
       - docker

   - name: Update apt packages
     become: true
     ansible.builtin.apt:
       update_cache: yes
     tags:
       - docker

   - name: Install docker
     become: true
     ansible.builtin.apt:
       name: docker-ce
       state: present
       update_cache: yes
     tags:
       - docker

   - name: Add remote "vagrant" user to "docker" group
     become: true
     ansible.builtin.user:
       name: vagrant
       group: "docker"
       append: yes
     tags:
       - docker

   - name: Install docker-compose
     become: true
     ansible.builtin.get_url:
       url : https://github.com/docker/compose/releases/download/v2.29.7/docker-compose-linux-x86_64
       dest: /usr/local/bin/docker-compose
       mode: 0777

   - name: Copy project
     ansible.builtin.copy:
       src: files
       dest: /home/vagrant

   - name: Reset ssh connection
     ansible.builtin.meta: reset_connection

   - name: Run container
     ansible.builtin.shell:
       cmd: "docker-compose -f docker-compose.yml up -d"
       chdir: /home/vagrant/files