---
- name: Base set up
  hosts: all
  become: true
  
  tasks:
   - name: Set repository on CentOS
     ansible.builtin.shell: sed -i s/mirror.centos.org/vault.centos.org/g /etc/yum.repos.d/*.repo &&
       sed -i s/^#.*baseurl=http/baseurl=http/g /etc/yum.repos.d/*.repo &&
       sed -i s/^mirrorlist=http/#mirrorlist=http/g /etc/yum.repos.d/*.repo
     when: (ansible_os_family == "RedHat")

   - name: Install software on CentOS
     ansible.builtin.yum:
       name:
         - traceroute
         - tcpdump
         - net-tools
       state: present
       update_cache: true
     when: (ansible_os_family == "RedHat")

   - name: Install software on Debian-based
     ansible.builtin.apt:
       name:
         - traceroute
         - tcpdump
         - net-tools
       state: present
       update_cache: true
     when: (ansible_os_family == "Debian")

- name: Set up vlan1
  hosts: testClient1,testServer1
  become: true
  tasks:
   - name: Set up vlan1
     ansible.builtin.template:
       src: ifcfg-vlan1.j2
       dest: /etc/sysconfig/network-scripts/ifcfg-vlan1
       owner: root
       group: root
       mode: 0644

   - name: Restart network for vlan1
     ansible.builtin.systemd:
       name: NetworkManager
       state: restarted

- name: Set up vlan2
  hosts: testClient2,testServer2
  become: true
  tasks:
   - name: Set up vlan2
     ansible.builtin.template:
       src: 50-cloud-init.yaml.j2
       dest: /etc/netplan/50-cloud-init.yaml
       owner: root
       group: root
       mode: 0644

   - name: Apply set up vlan2
     ansible.builtin.shell: netplan apply
     become: true

- name: Set up bond0
  hosts: inetRouter,centralRouter
  become: true
  tasks:
   - name: Set up ifcfg-bond0
     ansible.builtin.template:
       src: ifcfg-bond0.j2
       dest: /etc/sysconfig/network-scripts/ifcfg-bond0
       owner: root
       group: root
       mode: 0644

   - name: Set up eth1,eth2
     ansible.builtin.copy:
       src: "{{ item }}"
       dest: /etc/sysconfig/network-scripts/
       owner: root
       group: root
       mode: 0644
     with_items:
       - templates/ifcfg-eth1
       - templates/ifcfg-eth2

   - name: Restart hosts for bond0
     ansible.builtin.reboot:
       reboot_timeout: 3600